"""add_indexes_for_perf

Revision ID: 9fae457a1835
Revises: 175cbdd1e4a2
Create Date: 2026-02-26 12:06:37.332971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fae457a1835'
down_revision: Union[str, Sequence[str], None] = '175cbdd1e4a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_interview_messages_created_at'), 'interview_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_interview_messages_session_id'), 'interview_messages', ['session_id'], unique=False)
    op.create_index(op.f('ix_interview_messages_user_id'), 'interview_messages', ['user_id'], unique=False)
    op.create_index(op.f('ix_interview_sessions_created_at'), 'interview_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_interview_sessions_cv_id'), 'interview_sessions', ['cv_id'], unique=False)
    op.create_index(op.f('ix_interview_sessions_user_id'), 'interview_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_usage_daily_created_at'), 'usage_daily', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_daily_created_at'), table_name='usage_daily')
    op.drop_index(op.f('ix_interview_sessions_user_id'), table_name='interview_sessions')
    op.drop_index(op.f('ix_interview_sessions_cv_id'), table_name='interview_sessions')
    op.drop_index(op.f('ix_interview_sessions_created_at'), table_name='interview_sessions')
    op.drop_index(op.f('ix_interview_messages_user_id'), table_name='interview_messages')
    op.drop_index(op.f('ix_interview_messages_session_id'), table_name='interview_messages')
    op.drop_index(op.f('ix_interview_messages_created_at'), table_name='interview_messages')
    # ### end Alembic commands ###
